# Docker Compose pour le projet Diabète Test

services:
  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONT_END_PORT}:5173"
    environment:
      - VITE_API_URL=http://localhost:${BACKEND_PORT:-8000}
      - VITE_PREDICT_ENDPOINT=/predict
    env_file:
      - .env
    depends_on:
      - backend
    
  backend:
    build: ./BACKEND
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - .env