apiVersion: 2022-03-01
kind: ContainerApp
metadata:
  name: diabete-backend
spec:
  managedEnvironmentId: /subscriptions/{subscription-id}/resourceGroups/{resource-group}/providers/Microsoft.App/managedEnvironments/{environment-name}
  configuration:
    secrets:
    - name: registry-password
      value: "{registry-password}"
    registries:
    - server: "{registry-server}"
      username: "{registry-username}"
      passwordSecretRef: registry-password
    ingress:
      external: true
      targetPort: 8000
      transport: http
      corsPolicy:
        allowedOrigins: ["*"]
        allowedMethods: ["GET", "POST", "OPTIONS"]
        allowedHeaders: ["*"]
  template:
    containers:
    - image: {registry-server}/diabete-backend:latest
      name: diabete-backend
      resources:
        cpu: 0.5
        memory: 1Gi
      env:
      - name: PORT
        value: "8000"
    scale:
      minReplicas: 1
      maxReplicas: 10
      rules:
      - name: http-scale
        http:
          metadata:
            concurrentRequests: "30"